name: PMD Code Analysis

on:
  push:
  pull_request:

permissions: read-all

jobs:
  pmd-analysis:
    name: Run PMD Code Analysis
    runs-on: ubuntu-22.04
    permissions:
      security-events: write
      id-token: write

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - uses: pmd/pmd-github-action@v2
        with:
          version: '7.0.0-rc4'
          rulesets: 'rulesets/java/quickstart.xml'
          analyzeModifiedFilesOnly: false
          format: 'sarif' # Ensure PMD outputs SARIF format
          outputFile: 'pmd-report.sarif'
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: pmd-report.sarif
